name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build React app
      run: npm run build
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli
      
    - name: Sync Capacitor to Android
      run: npx cap sync android
      
    - name: Decode Keystore
      run: |
        mkdir -p android/app
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/garden-alchemy-strong.keystore
        
    - name: Build signed APK
      run: |
        cd android
        chmod +x gradlew
        ANDROID_COMPILE_SDK=34 ANDROID_BUILD_TOOLS=34.0.0 ANDROID_SDK_ROOT=$ANDROID_HOME ./gradlew assembleRelease \
        -Pandroid.injected.signing.store.file=app/garden-alchemy-strong.keystore \
        -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
        -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
        -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}
        
    - name: Upload signed APK
      uses: actions/upload-artifact@v4
      with:
        name: signed-apk
        path: android/app/build/outputs/apk/release/app-release.apk
